apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejsport-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nodejsport
  template:
    metadata:
      labels:
        app: nodejsport
    spec:
      containers:
        - name: nodejsport-container
          image: 222634382744.dkr.ecr.eu-west-2.amazonaws.com/nodejsport:latest
          ports:
            - containerPort: 3000
